{-# LANGUAGE OverloadedStrings #-}

-- |
-- Build orchestration for the Julia backend.
--
-- Reads @corefn.json@ for every compiled module, emits one Julia module
-- file per PureScript module, the runtime, the built-in FFI shims, a
-- topologically-ordered @loader.jl@, and (when a Main module exists) a
-- @main.jl@ entry point so the program runs with
-- @julia OUTPUT_DIR\/main.jl@.
--
module Language.PureScript.Julia.Make
  ( compile
  , CompileOptions(..)
  ) where

import Prelude

import Control.Monad (forM, forM_, unless, when)
import Data.Aeson (decodeFileStrict)
import Data.Aeson.Types (parseMaybe)
import Data.List (find)
import qualified Data.Map.Strict as Map
import Data.Maybe (catMaybes)
import qualified Data.Set as Set
import qualified Data.Text as T
import qualified Data.Text.IO as TIO
import System.Directory (createDirectoryIfMissing, doesDirectoryExist, doesFileExist, copyFile)
import System.FilePath ((</>), takeFileName)
import System.FilePath.Glob (glob)

import qualified Language.PureScript as P
import qualified Language.PureScript.CoreFn as CoreFn
import qualified Language.PureScript.CoreFn.FromJSON as CoreFn

import Language.PureScript.Julia.CodeGen (generateModuleJl)
import Language.PureScript.Julia.CodeGen.Common (jlModuleName, jlFileName, jlForeignFileName)
import Language.PureScript.Julia.Foreigns (builtinForeigns)

data CompileOptions = CompileOptions
  { inputDir :: FilePath    -- ^ Directory containing corefn.json files (usually "output")
  , outputDir :: FilePath   -- ^ Directory for Julia output (usually "output-jl")
  }

-- | Compile all modules in the input directory
compile :: CompileOptions -> IO ()
compile opts = do
  let coreFnGlob = inputDir opts </> "*" </> "corefn.json"
  corefnFiles <- glob coreFnGlob

  when (null corefnFiles) $
    putStrLn "No corefn.json files found. Run 'spago build' (with a backend configured) first."

  unless (null corefnFiles) $ do
    putStrLn $ "Found " ++ show (length corefnFiles) ++ " modules to compile"
    createDirectoryIfMissing True (outputDir opts)

    -- Parse all modules up front (we need the import graph for the loader)
    mods <- fmap catMaybes . forM corefnFiles $ \corefnFile -> do
      mJson <- decodeFileStrict corefnFile
      case mJson >>= parseMaybe CoreFn.moduleFromJSON of
        Nothing -> do
          putStrLn $ "Error: failed to parse " ++ corefnFile
          return Nothing
        Just (_version, cfModule) -> return (Just cfModule)

    -- Emit each module
    forM_ mods $ \cfModule -> do
      let mn = CoreFn.moduleName cfModule
          outFile = outputDir opts </> jlFileName mn
      TIO.writeFile outFile (moduleFile cfModule)
      putStrLn $ "Compiled: " ++ T.unpack (jlModuleName mn)

    -- Runtime + built-in FFI shims; user shims (ffi-jl/) copied last so they win
    generateRuntime (outputDir opts)
    forM_ builtinForeigns $ \(name, content) ->
      TIO.writeFile (outputDir opts </> name) content
    copyUserForeigns (outputDir opts)

    -- Warn about reachable modules with foreign imports but no shim on disk
    let mainMod = find (\m -> CoreFn.moduleName m == P.ModuleName "Main") mods
        ordered = loadOrder mods mainMod
        byName = Map.fromList [(CoreFn.moduleName m, m) | m <- mods]
    forM_ ordered $ \mn ->
      forM_ (Map.lookup mn byName) $ \m ->
        unless (null (CoreFn.moduleForeign m)) $ do
          let shim = outputDir opts </> jlForeignFileName mn
          exists <- doesFileExist shim
          unless exists $
            putStrLn $ "Warning: " ++ T.unpack (jlModuleName mn)
                     ++ " has foreign imports but no " ++ takeFileName shim
                     ++ " - provide one in ffi-jl/"

    -- Loader (deps-first include order) and entry point
    TIO.writeFile (outputDir opts </> "loader.jl") (loaderFile mods ordered byName)
    case mainMod of
      Just _ -> do
        TIO.writeFile (outputDir opts </> "main.jl") $ T.unlines
          [ "# Generated by purejl - program entry point"
          , "include(\"loader.jl\")"
          , "Main_.main()"
          ]
        putStrLn $ "Run with: julia " ++ (outputDir opts </> "main.jl")
      Nothing ->
        putStrLn "No Main module found - generated loader.jl only"

    putStrLn "Done!"

-- | Full text of one generated module file
moduleFile :: CoreFn.Module CoreFn.Ann -> T.Text
moduleFile cfModule =
  let mn@(P.ModuleName name) = CoreFn.moduleName cfModule
      isPrimModule (P.ModuleName n) = T.isPrefixOf "Prim" n
      imports = dedupe
        [ depMn
        | depMn <- map snd (CoreFn.moduleImports cfModule)
        , depMn /= mn
        , not (isPrimModule depMn)
        ]
      hasForeign = not (null (CoreFn.moduleForeign cfModule))
  in T.unlines $
       [ "# Generated by purejl from PureScript module: " <> name
       , "# Do not edit this file directly"
       , "module " <> jlModuleName mn
       , "import ..PurejlRuntime: _runtime_lazy, _js_number_string"
       ]
       ++ [ "import .." <> jlModuleName depMn | depMn <- imports ]
       ++ (if hasForeign
             then [ "include(\"" <> T.pack (jlForeignFileName mn) <> "\")" ]
             else [])
       ++ [ "" , generateModuleJl cfModule , "end" ]

dedupe :: Ord a => [a] -> [a]
dedupe = go Set.empty
  where
    go _ [] = []
    go seen (x:xs)
      | x `Set.member` seen = go seen xs
      | otherwise = x : go (Set.insert x seen) xs

-- | Topologically-ordered module list (dependencies first). When a Main
-- module exists, restrict to its transitive closure; otherwise load
-- everything.
loadOrder :: [CoreFn.Module CoreFn.Ann] -> Maybe (CoreFn.Module CoreFn.Ann) -> [P.ModuleName]
loadOrder mods mainMod =
  let compiled = Set.fromList (map CoreFn.moduleName mods)
      depsOf = Map.fromList
        [ ( CoreFn.moduleName m
          , dedupe [ d | d <- map snd (CoreFn.moduleImports m)
                       , d /= CoreFn.moduleName m
                       , d `Set.member` compiled ] )
        | m <- mods ]
      roots = case mainMod of
        Just m -> [CoreFn.moduleName m]
        Nothing -> map CoreFn.moduleName mods
      -- DFS post-order: dependencies emitted before dependents
      visit (visited, acc) mn
        | mn `Set.member` visited = (visited, acc)
        | otherwise =
            let (visited', acc') =
                  foldl visit (Set.insert mn visited, acc)
                        (Map.findWithDefault [] mn depsOf)
            in (visited', acc' ++ [mn])
  in snd (foldl visit (Set.empty, []) roots)

-- | The loader: runtime first, then modules deps-first
loaderFile :: [CoreFn.Module CoreFn.Ann]
           -> [P.ModuleName]
           -> Map.Map P.ModuleName (CoreFn.Module CoreFn.Ann)
           -> T.Text
loaderFile _mods ordered _byName = T.unlines $
  [ "# Generated by purejl - includes all modules in dependency order"
  , "include(\"purejl_runtime.jl\")"
  ]
  ++ [ "include(\"" <> T.pack (jlFileName mn) <> "\")" | mn <- ordered ]

-- | Copy user-supplied FFI shims from ./ffi-jl into the output directory
copyUserForeigns :: FilePath -> IO ()
copyUserForeigns outDir = do
  let ffiDir = "ffi-jl"
  exists <- doesDirectoryExist ffiDir
  when exists $ do
    files <- glob (ffiDir </> "*.jl")
    forM_ files $ \f -> do
      copyFile f (outDir </> takeFileName f)
      putStrLn $ "FFI (user): " ++ takeFileName f

-- | Runtime support module
generateRuntime :: FilePath -> IO ()
generateRuntime dir = TIO.writeFile (dir </> "purejl_runtime.jl") $ T.unlines
  [ "# PureScript Julia Runtime"
  , "# Generated by purejl"
  , "module PurejlRuntime"
  , ""
  , "export _runtime_lazy, _js_number_string"
  , ""
  , "# JS Number.prototype.toString formatting, built on Julia's shortest-"
  , "# roundtrip repr (same digits, different placement rules). Decimal"
  , "# notation for 1e-6 <= |n| < 1e21, exponential with explicit sign"
  , "# otherwise, integer-valued doubles without a point. Used by the"
  , "# Data.Show and Data.Number.Format shims."
  , "function _js_number_string(n)"
  , "    if Base.isnan(n); return \"NaN\"; end"
  , "    if n == Base.Inf; return \"Infinity\"; end"
  , "    if n == -Base.Inf; return \"-Infinity\"; end"
  , "    if n == 0.0; return \"0\"; end"
  , "    s = Base.string(n)"
  , "    neg = Base.startswith(s, \"-\")"
  , "    if neg; s = s[2:end]; end"
  , "    parts = Base.split(s, \"e\")"
  , "    mant = parts[1]"
  , "    ex = Base.length(parts) == 2 ? Base.parse(Base.Int, parts[2]) : 0"
  , "    dot = Base.findfirst('.', mant)"
  , "    intlen = dot === nothing ? Base.length(mant) : dot - 1"
  , "    digits = Base.replace(mant, \".\" => \"\")"
  , "    pp = intlen + ex      # decimal point position: n = 0.digits * 10^pp"
  , "    k0 = Base.length(digits)"
  , "    digits = Base.lstrip(digits, '0')"
  , "    pp -= k0 - Base.length(digits)"
  , "    digits = Base.rstrip(digits, '0')"
  , "    k = Base.length(digits)"
  , "    body = if k <= pp <= 21"
  , "        digits * Base.repeat(\"0\", pp - k)"
  , "    elseif 0 < pp <= 21"
  , "        digits[1:pp] * \".\" * digits[(pp + 1):end]"
  , "    elseif -6 < pp <= 0"
  , "        \"0.\" * Base.repeat(\"0\", -pp) * digits"
  , "    else"
  , "        e = pp - 1"
  , "        Base.string(digits[1]) * (k > 1 ? \".\" * digits[2:end] : \"\") *"
  , "            \"e\" * (e >= 0 ? \"+\" : \"-\") * Base.string(Base.abs(e))"
  , "    end"
  , "    neg ? \"-\" * body : body"
  , "end"
  , ""
  , "# Lazy initialization wrapper for mutually recursive top-level bindings."
  , "# state: 0 = uninitialized, 1 = initializing, 2 = done"
  , "function _runtime_lazy(name, module_name, init)"
  , "    state = Base.Ref(0)"
  , "    val = Base.Ref{Any}(nothing)"
  , "    function thunk()"
  , "        if state[] == 2"
  , "            return val[]"
  , "        end"
  , "        if state[] == 1"
  , "            Base.error(name * \" was needed before it finished initializing (module \" * module_name * \")\")"
  , "        end"
  , "        state[] = 1"
  , "        val[] = init()"
  , "        state[] = 2"
  , "        val[]"
  , "    end"
  , "    thunk"
  , "end"
  , ""
  , "end"
  ]
